AWSTemplateFormatVersion: '2010-09-09'
Description: THIS IS A TEST

Parameters:
  KeyPairName:
    Description: The name of the EC2 Key Pair to allow SSH access
    Type: String

Resources:
  server:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      ImageId: ami-08c40ec9ead489470
      SecurityGroupIds:
        - !Ref ec2

  ec2:
    Type: AWS::EC2::Securitygroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref server
  PublicIp:
    Description: Public IP 
    Value: !GetAtt server.PublicIp