name: AWS

on:
  push:
    branches: [master]

permissions:
    id-token: write   
    contents: read 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Deploy Infrastructure
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          stack-name: s3
          template-file: ../infrastructure/cloudFormation.yaml
          capabilities: CAPABILITY_IAM